### ISSUE TITLE
New name instead of BernardQueueing

### ISSUE THREAD

**Issue by sagikazarmark** [thephpleague/tactician-bernard#1]
Ideas plz, this name gave me cancer.

**Comment by rosstuck** [comment]
Just League\Tactician\Bernard then? We're probably going to have other Queuing packages in the future so calling it League\Tactician\Queuing might be a bit too broad.

**Comment by sagikazarmark** [comment]
That might be better. I know there was arguments against it, because Bernard is too vague, but it is not the package name that should give the description, is it?

**Comment by sagikazarmark** [comment]
@rosstuck Is `tactician-bernard` and `League\Tactician\Bernard` fine for you?

**Comment by rosstuck** [comment]
Works for me! We can document the queueing aspect in the manual.

**Comment by sagikazarmark** [comment]
OK, let's leave it after the PR gets merge to make sure we don't get lost in some composer configuration madness.

**Comment by sagikazarmark** [comment]
@rosstuck as soon as the middleware architecture is finished I am going to open a PR which does every in-repo modifications to be able to rename it to `tactician-bernard`. After that the following should be done:
- Renaming this repo to `tactician-bernard`
- Deleting it from packagist as exactly 0 downloads happend so far
- Readding the package to packagist with the new name
- Updating travis and scrutinizer

I am assigning this to you @rosstuck and asking you to do what needs to be done when the time comes. :sunglasses:

**Comment by rosstuck** [comment]
Aight, can do. :)

**Comment by sagikazarmark** [comment]
@rosstuck see #10

**Comment by rosstuck** [comment]
Okay, should be done. Scrutinizer is showing NaN for code coverage but I'm going to assume that's a temporary issue for now.

**Comment by sagikazarmark** [comment]
Yeah, it should be temporary. If you review/merge the docs PR, I am going to tag v0.1.

**Comment by sagikazarmark** [comment]
Thanks
