### ISSUE TITLE
Site with documentation is disabled

### ISSUE THREAD

**Issue by akireikin** [thephpleague/tactician-bernard#35]
[http://tactician.thephpleague.com/plugins/bernard/](http://tactician.thephpleague.com/plugins/bernard/)

**Comment by sagikazarmark** [comment]
What do you mean by "disabled"? I can open it.

**Comment by akireikin** [comment]
Got it, for some reason my Internet provider doesn't like this site.

**Comment by rosstuck** [comment]
Thanks for reporting it! If it doesn't infringe on your privacy too much and you have any ideas about the word/phrase that might be blocked, please let us know and we'll see if we can reword it in a way that doesn't trigger the filter. Thanks!
