### ISSUE TITLE
Add QueueEverythingMiddleware

### ISSUE THREAD

**Issue by sagikazarmark** [thephpleague/tactician-bernard#36]
Although I know we agreed on this quite some time ago, but it still seems to me fundamentally wrong that we require devs to use a marker interface to decide if a command should be queued or not. Although it's okay for me to have this possibility, I would add a QueueEverythingMiddleware which wraps all commands in a QueueCommand object (which does not already implement the relevant interface AND NOT a QueuedCommand to prevent infinite loops). Having this would help in cases where we just want every command to be queued. WDYT @rosstuck ?

**Comment by rosstuck** [comment]
In short, agreed. Go for it! :+1:
