### ISSUE TITLE
Typo in documentation

### ISSUE THREAD

**Issue by chapay** [thephpleague/tactician-bernard#51]
Unfortunately I did not find the place where I could send a PR with proper fixes, so I decided to open an issue.

The fix is easy - there must be `SameBusReceiver` instead of `SingleBusReceiver` here: http://tactician.thephpleague.com/plugins/bernard/

Thanks for such amazing OS project!

**Comment by rosstuck** [comment]
Hi Andrey,

Great catch! Thanks for your kind words. :)

If you'd still like to send a PR, the docs are on the gh-pages branch of
the main Tactician repo. Sorry it was hard to find, it's a GitHub
convention. If you can't, I'll try to fix it later this week.

Thanks again!

**Comment by chapay** [comment]
Though now it seems obvious for me, maybe it's better to add a line about it to `CONTRIBUTING.md` file. :)

I created a PR with the fix: https://github.com/thephpleague/tactician/pull/112

You are welcome!

**Comment by rosstuck** [comment]
That's a really good idea, I'll do that! :)

**Comment by chapay** [comment]
Will close it as fixed then, thanks!
